post_install() {
  /opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility certificate generate
  /opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility service install
}

pre_upgrade() {
  /opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility service uninstall
}

post_upgrade() {
  /opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility certificate generate
  /opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility service install
}

post_remove() {
  /opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility service uninstall
}