#!/usr/bin/env bash

csource="${BASH_SOURCE[0]}"
while [ -h "$csource" ] ; do csource="$(readlink "$csource")"; done
root="$( cd -P "$( dirname "$csource" )/../" && pwd )"

. "${root}/.ci/load-ci.sh"
pushd "${root}"

cache_name="${1}"
source="${2}"

# Sanity checks
if [ -z "${source}" ]; then
    failure "source files/directory for cache required"
fi

if [ -z "${cache_name}" ]; then
    failure "name of cache required"
fi

if [ ! -e "${source}" ]; then
    failure "source path provided for cache does not exist (${source})"
fi

if github_draft_release_exists "${repo_owner}" "${repo_name}" "${cache_name}"; then
    printf "Cache item already exists (name: %s repository: %s)" "${cache_name}" "${repo_owner}/${repo_name}" >&2
    exit 1
fi

github_draft_release "${repo_owner}" "${repo_name}" "${cache_name}" "${source}"
