#!/usr/bin/env bash

# Output to stdout if we aren't on a runner
if [ -z "${GITHUB_OUTPUT}" ]; then
    GITHUB_OUTPUT="/dev/stdout"
fi

csource="${BASH_SOURCE[0]}"
while [ -h "$csource" ] ; do csource="$(readlink "$csource")"; done
root="$( cd -P "$( dirname "$csource" )/../" && pwd )"

. "${root}/.ci/load-ci.sh"
pushd "${root}"

version="$(<./versions/desktop.txt)"
release_tag="desktop-v${version}"

tmpdir="$(mktemp -d -p ./)" ||
    failure "Failed to create temporary directory for plugin gem download"

pushd "${tmpdir}"
tmpdir="$(pwd)" ||
    failure "Failed to get full path of download directory"
github_release_assets "vagrant-vmware-desktop" "${release_tag}" ".gem"
popd

gem_list=( "${tmpdir}/"* )
gem="${gem_list[0]}"

if [ ! -f "${gem}" ]; then
    failure "Expected plugin gem download was not found"
fi

printf "plugin-path=%s\n" "${gem}" >> "${GITHUB_OUTPUT}"
