#!/usr/bin/env bash
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

csource="${BASH_SOURCE[0]}"
while [ -h "$csource" ] ; do csource="$(readlink "$csource")"; done
root="$( cd -P "$( dirname "$csource" )/../" && pwd )"

. "${root}/.ci/load-ci.sh"

pushd "${root}"

if [ -z "${tag}" ]; then
    failure "Sync requires tag expected to be provided via common library"
fi

# Configure hashibot user
hashibot_git

# Define the remote repository
remote_repo_name="vagrant-vmware-desktop-builder"

info "Adding remote repository: %s" "${remote_repo_name}"
git remote add mirror "https://${HASHIBOT_USERNAME}:${HASHIBOT_TOKEN}@github.com/${repo_owner}/${remote_repo_name}" ||
    failure "Failed to configure remote mirror"

info "Validating mirror configuration"
git remote update mirror ||
    failure "Failed to update mirror repository"

info "Pushing tag to mirror (tag: %s)" "${tag}"
git push mirror "${tag}" ||
    failure "Failed to push tag (%s) to mirror repository (%s)" "${tag}" "${remote_repo_name}"
