on:
  push:
    tags:
      - 'desktop-v*'

jobs:
  release:
    if: github.repository == 'hashicorp/vagrant-vmware-desktop-builder'
    name: Vagrant VMware Desktop Plugin Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # set this so we can delete the branch
      - name: Fetch Release RubyGem
        id: fetch
        run: ./.ci/download-release-plugin
      - name: Doormat Configuration
        uses: hashicorp/doormat-action@v1
        with:
          aws-role-arn: ${{ vars.HASHIGEMS_DOORMAT_ROLE_ARN }}
      - name: Configure AWS
        run: aws sts get-caller-identity
      - name: Release Vagrant VMware Desktop Plugin
        run: ./.ci/release-hashigems "${PLUGIN_PATH}"
        env:
          PLUGIN_PATH: ${{ steps.fetch.outputs.plugin-path }}
          HASHIGEMS_METADATA_BUCKET: ${{ vars.HASHIGEMS_METADATA_BUCKET }}
          HASHIGEMS_PUBLIC_BUCKET: ${{ vars.HASHIGEMS_PUBLIC_BUCKET }}
          HASHIGEMS_CLOUDFRONT_ID: ${{ vars.HASHIGEMS_DISTRIBUTION_ID }}
