on:
  push:
    tags:
      - 'desktop-v*'

jobs:
  rubygems-release:
    if: github.repository == 'hashicorp/vagrant-vmware-desktop-builder'
    name: Vagrant VMware Desktop RubyGems Release
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.small']
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder rubygems_api_key;
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder vagrant_vmware_desktop_builder_repo_token;
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder vagrant_vmware_desktop_repo_token;
      - name: Code Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - name: Setup Ruby
        uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 # v1.190.0
        with:
          ruby-version: ruby
      - name: Build Vagrant VMware Desktop Plugin
        id: build
        run: ./.ci/build-plugin
      - name: Create GitHub release
        run: ./.ci/release-plugin-github "${GEM_ARTIFACT}"
        env:
          GEM_ARTIFACT: ${{ steps.build.outputs.gem-path }}
          GITHUB_TOKEN: ${{ steps.secrets.outputs.vagrant_vmware_desktop_repo_token }}
      - name: Publish RubyGems.org
        run: ./.ci/release-rubygems "${PLUGIN_PATH}"
        env:
          PLUGIN_PATH: ${{ steps.build.outputs.gem-path }}
          RUBYGEMS_API_KEY: ${{ steps.secrets.outputs.rubygems_api_key }}
  hashigems-release:
    if: github.repository == 'hashicorp/vagrant-vmware-desktop-builder'
    name: Vagrant VMware Desktop HashiGems Release
    needs: [rubygems-release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Fetch Release RubyGem
        id: fetch
        run: ./.ci/download-release-plugin
      - name: Doormat Configuration
        uses: hashicorp/doormat-action@v1
        with:
          aws-role-arn: ${{ vars.HASHIGEMS_DOORMAT_ROLE_ARN }}
      - name: Configure AWS
        run: aws sts get-caller-identity
      - name: Release Vagrant VMware Desktop Plugin
        run: ./.ci/release-hashigems "${PLUGIN_PATH}"
        env:
          PLUGIN_PATH: ${{ steps.fetch.outputs.plugin-path }}
          HASHIGEMS_METADATA_BUCKET: ${{ vars.HASHIGEMS_METADATA_BUCKET }}
          HASHIGEMS_PUBLIC_BUCKET: ${{ vars.HASHIGEMS_PUBLIC_BUCKET }}
          HASHIGEMS_CLOUDFRONT_ID: ${{ vars.HASHIGEMS_DISTRIBUTION_ID }}
