on:
  push:
    branches:
      - main
      - 'test-*'
    paths:
      - 'go_src/**'
      - 'go.*'
  pull_request:
    branches:
      - main
    paths:
      - 'go_src/**'
      - 'go.*'

jobs:
  tests:
    if: github.repository == 'hashicorp/vagrant-vmware-desktop'
    runs-on: ubuntu-latest
    name: Vagrant VMware Utility Tests
    steps:
      - name: Code Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
      - name: Run Tests
        run: make test
