on:
  push:
    tags:
      - 'utility-v*'
      - '!utility-v*\+*'

jobs:
  build-packages:
    if: github.repository == 'hashicorp/vagrant-vmware-desktop-builder'
    name: Build packages
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/build-utility-packages.yml
    secrets: inherit
  release:
    if: github.repository == 'hashicorp/vagrant-vmware-desktop-builder'
    name: Release packages
    needs: [build-packages]
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.small']
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder hashicorp_release_github_token;
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder releases_api_production_host;
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder releases_api_production_key;
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder releases_api_staging_host;
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder releases_api_staging_key;
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder releases_aws_access_key_id;
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder releases_aws_secret_access_key;
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder releases_aws_role_arn;
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder signore_client_id;
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder signore_client_secret;
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder signore_gpg_signer;
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Fetch linux packages
        run: ./.ci/restore-cache "${CACHE_ID}" ./pkg
        env:
          CACHE_ID: ${{ needs.build-packages.outputs.linux-cache-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch macOS packages
        run: ./.ci/restore-cache "${CACHE_ID}" ./pkg
        env:
          CACHE_ID: ${{ needs.build-packages.outputs.macos-cache-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch windows packages
        run: ./.ci/restore-cache "${CACHE_ID}" ./pkg
        env:
          CACHE_ID: ${{ needs.build-packages.outputs.windows-cache-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update macOS package name
        run: ./.ci/utility-macos-rename-release ./pkg
      - name: Release Packages
        run: ./.ci/utility-packages-release "${UTILITY_VERSION}" "./pkg"
        env:
          HASHIBOT_TOKEN: ${{ steps.secrets.outputs.hashicorp_release_github_token }}
          UTILITY_VERSION: ${{ needs.build-packages.outputs.utility-version }}
          SIGNORE_SIGNER: ${{ steps.secrets.outputs.signore_gpg_signer }}
          SIGNORE_CLIENT_ID: ${{ steps.secrets.outputs.signore_client_id  }}
          SIGNORE_CLIENT_SECRET: ${{ steps.secrets.outputs.signore_client_secret }}
          RELEASE_AWS_ACCESS_KEY_ID: ${{ steps.secrets.outputs.releases_aws_access_key_id }}
          RELEASE_AWS_SECRET_ACCESS_KEY: ${{ steps.secrets.outputs.releases_aws_secret_access_key }}
          RELEASE_AWS_ASSUME_ROLE_ARN: ${{ steps.secrets.outputs.releases_aws_role_arn }}
          HC_RELEASES_PROD_SNS_TOPIC: ${{ vars.HASHICORP_RELEASES_SNS_ARN }}
          HC_RELEASES_PROD_HOST: ${{ steps.secrets.outputs.releases_api_production_host }}
          HC_RELEASES_PROD_KEY: ${{ steps.secrets.outputs.releases_api_production_key }}
          HC_RELEASES_STAGING_HOST: ${{ steps.secrets.outputs.releases_api_staging_host }}
          HC_RELEASES_STAGING_KEY: ${{ steps.secrets.outputs.releases_api_staging_key }}
          HASHICORP_PUBLIC_GPG_KEY_ID: ${{ vars.HASHICORP_GPG_SIGNING_ID }}
