on:
  push:
    tags:
      - 'utility-v*'
      - '!utility-v*\+*'

jobs:
  build-packages:
    if: github.repository == 'hashicorp/vagrant-vmware-desktop-builder'
    name: Build packages
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: ./.github/workflows/build-utility-packages.yml
    secrets: inherit
  release:
    if: github.repository == 'hashicorp/vagrant-vmware-desktop-builder'
    needs: [build-packages]
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.small']
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder releases_host;
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder releases_key;
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder releases_aws_access_key_id;
            kv/data/github/hashicorp/vagrant-vmware-desktop-builder releases_aws_secret_access_key;
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Fetch linux packages
        run: ./.ci/restore-cache "${CACHE_ID}" ./pkg
        env:
          CACHE_ID: ${{ needs.info.outputs.linux-cache-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Fetch macOS packages
      #   run: ./.ci/restore-cache "${CACHE_ID}" ./pkg
      #   env:
      #     CACHE_ID: ${{ needs.info.outputs.macos-cache-id }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch windows packages
        run: ./.ci/restore-cache "${CACHE_ID}" ./pkg
        env:
          CACHE_ID: ${{ needs.info.outputs.windows-cache-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release Packages
        run: . ./.ci/load-ci.sh && hashicorp_release "./pkg" "vagrant-vmware-utility" "${UTILITY_VERSION}"
        env:
          UTILITY_VERSION: ${{ needs.build-packages.outputs.utility-version }}
          RELEASE_AWS_ACCESS_KEY_ID: ${{ steps.secrets.outputs.release_aws_access_key_id }}
          RELEASE_AWS_SECRET_ACCESS_KEY: ${{ steps.secrets.outputs.release_aws_secret_access_key }}
          RELEASE_AWS_ASSUME_ROLE_ARN: ${{ steps.secrets.outputs.release_aws_assume_role_arn }}
          HC_RELEASES_PROD_HOST: ${{ steps.secrets.outputs.hc_releases_prod_host }}
          HC_RELEASES_PROD_KEY: ${{ steps.secrets.outputs.hc_releases_prod_key }}
          HC_RELEASES_STAGING_HOST: ${{ steps.secrets.outputs.hc_releases_staging_host }}
          HC_RELEASES_STAGING_KEY: ${{ steps.secrets.outputs.hc_releases_staging_key }}
