on:
  push:
    branches:
      - 'build-utility-*'
  schedule:
    - cron: '15 1 * * *'
  workflow_dispatch:

jobs:
  build-utilities:
    if: github.repository == 'hashicorp/vagrant-vmware-desktop'
    name: Development Utility Builds
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: go.mod
      - name: Get info
        id: info
        run: ./.ci/utility-bins-information
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish utilities
        if: ${{ steps.info.outputs.utility-bins-release-exists != 'true' }}
        run: ./.ci/utility-binaries-prerelease "${UTILITY_VERSION}"
        env:
          UTILITY_VERSION: ${{ steps.info.outputs.utility-bins-version }}
          EVENT_NAME: ${{ github.event_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
